# Generated by Django 3.1.7 on 2021-03-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdatabase',
            name='name',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='songdatabase',
            name='title',
            field=models.CharField(max_length=900),
        ),
    ]
