# Generated by Django 3.1.7 on 2021-03-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0001_initial'),
        ('radios', '0002_auto_20210304_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTitler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rds', models.CharField(max_length=150)),
                ('listeners', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.songdatabase')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radios.station')),
            ],
        ),
    ]
