# Generated by Django 3.1.7 on 2021-03-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('radios', '0002_auto_20210304_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listeners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listeners', models.SmallIntegerField()),
                ('time', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='radios.station')),
            ],
        ),
    ]
