# Generated by Django 3.1.7 on 2021-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='listenersurl',
            field=models.ManyToManyField(related_name='listeners', to='radios.Stream'),
        ),
    ]
