# Generated by Django 3.1.7 on 2021-03-04 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('listeners', '0001_initial'),
        ('song', '0001_initial'),
        ('radios', '0002_auto_20210304_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Station',
            new_name='RStation',
        ),
    ]
