# Generated by Django 3.1.7 on 2021-03-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0003_auto_20210304_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rstation',
            name='listenersurl',
            field=models.ManyToManyField(blank=True, null=True, related_name='listeners', to='radios.Stream'),
        ),
    ]
